### ISSUE TITLE
serviceEndpoint expects a service connection of type azureRM but the provided service connection ************ is of type devCenter

### ISSUE THREAD

**Issue by christian-eaton** [microsoft/windows-dev-center-vsts-extension#119]
We have been using store-publish(currently @3) for quite some time.  We had a successfull deployment 2 weeks ago.  However, over the last 2 weeks, our deployment pipeline has begun to get the following error:

The pipeline is not valid. Job Deploy: Step input serviceEndpoint expects a service connection of type azureRM but the provided service connection *********** is of type devCenter

We have not changed anything with the YAML nor the service connection that it uses in quite some time.  What is going on?  Was a change made to the extension that would cause this?

**Comment by louis-wuitton** [comment]
The major version 3 extension only supports AzureRM typed service connection and you can configure it using workload identity federation instead of secrets. I think you can check the service connection you are using and make sure it's indeed of type AzureRM configured. It's possible that you only upgraded the major version number but you didn't switch to a different type of service connection.

**Comment by christian-eaton** [comment]
Thank you for the insight.  That appears to be the issue.
