### ISSUE TITLE
Option for waiting to Finish the Submission

### ISSUE THREAD

**Issue by baumerik** [Microsoft/windows-dev-center-vsts-extension#23]
Hi,

The waiting for processing the publish in the windows store can take a long time. Can you provide an option so that the task finished after commiting this submission and not to wait until the whole process is finished? Like "Fire and Forget".

I my case I upload to Apple and Play Store too. If I have to wait on all of this stores my build will run too long.

Thanks
Erik

**Comment by kp101090** [comment]
Hey baumerik,
Can you elaborate more on what exactly you are trying to do? Are you using publish task in a Build Definition or Release Definition?
**If you are using Release Definition**, you can configure the release definition to run the environments in parallel so that you are not waiting for one environment to finish while other one is running (more information can be found [here](https://www.visualstudio.com/en-us/docs/release/author-release-definition/understanding-environments#parallel-forked-and-joined-deployments)).
**If you are using Build Definition** (essentially producing an artifact), you can link this build\artifact in a release definition in which you will have three different environments uploading to three different endpoints (Apple Store, Play Store, Windows Store) and set to run in parallel.

Let us know what you want to achieve so we can help better!

**Comment by vlechenko** [comment]
Hi All,

I have this issue too.
I have huge count of lines in log:
Submission status for "applications/9WZDNCRDM0S9/flights/4cae27e1-e57d-4fd5-8b82-dca949a30bff/submissions/1152921504626175794"Certification

I want no waiting for certification complete because all of what I need it is only submit packages.

**Comment by baumerik** [comment]
Hi @kp101090,
I think about a "refactoring" of our build and release process but then the agent will blocked to just for waiting. for a Live deployment it's okay but for test deployments it should be a stupid waiting und blocking process. So I think this is feature for a release Definition too.

Thanks
Erik

**Comment by kp101090** [comment]
@baumerik @vlechenko We saw you pull request and we are pleased to see people taking actively contributing to the community! We really appreciate that! In order to provide best user experience considering different scenarios, we are having conversation with Windows Store and API team. We will get back to you soon. Thank you very much for your patience!

**Comment by nickward13** [comment]
I would like this feature too - it would be great to not have the VSTS build pipeline waiting for the store submission to complete, but rather just kick it off, and then continue on processing the pipeline.

**Comment by zurdev** [comment]
Added Skip polling Checkbox
