### ISSUE TITLE
Add an option for Release notes

### ISSUE THREAD

**Issue by Brian-Ding** [Microsoft/windows-dev-center-vsts-extension#31]
it would be great if the team could add an option to use a text file as release notes for each submission

**Comment by ChristopheLav** [comment]
Hello Brian,

This possibility already exists with metadata update in app submissions task (flight task doesn't have metedata because Windows Store doesn't support it for Flights submissions).

Metadata structure (JSON or TXT) is documented here: https://marketplace.visualstudio.com/items?itemName=MS-RDX-MRO.windows-store-publish
________________________________
De : Brian Ding <notifications@github.com>
Envoyé : vendredi 10 mars 2017 08:28:57
À : Microsoft/windows-dev-center-vsts-extension
Cc : Subscribed
Objet : [Microsoft/windows-dev-center-vsts-extension] Add an option for Release notes (#31)


it would be great if the team could add an option to use a text file as release notes for each submission

**Comment by MPEV** [comment]
Is this supported now? 

https://docs.microsoft.com/en-us/windows/uwp/monetize/create-a-flight-submission
https://docs.microsoft.com/en-us/windows/uwp/monetize/update-a-flight-submission

**Comment by ChristopheLav** [comment]
@MPEV, sorry I don't see this information on your pages. Certification notes (for Microsoft testers only) isn't Release notes (public and visible in the Store). API hasn't change recently in this area and I doubt it will be change soon because Windows Store doesn't support metadata for flight submissions: only for a public Release.

If you want more options for testing packages, HockerApp/MobileCenter may help you ;)

**Comment by elendil326** [comment]
Closing as resolved.
