### ISSUE TITLE
Add option to disable automatic submission to certification

### ISSUE THREAD

**Issue by jmvillagra** [Microsoft/windows-dev-center-vsts-extension#54]
Hi
Would be possible to add a new option to disable the automatic submission to certification? 
It would be interesting for cases where it needs a manual metadata update before submitting it to the store.

In this case, the task only needs to upload the packages to the submission in progress (or create a new one) and finalize if the upload was successful.

Thanks,
Jose.

**Comment by elendil326** [comment]
Thanks for creating the issue @jmvillagra . The extension was built thinking on Continuous Integration scenarios. This means for the extension to mainly provide tools to automate the normal workflow of deployment to the Store and avoid any human interaction. 

Although it would be possible to implement your suggestion, it does not align with the goals of the extension. Also, it is not recommended to manually manipulate a submission created via the API, since it also creates changes in the background that are not reflected through the Windows Dev Center web page.

The extension currently supports metadata automation, refer to the ReadMe for how to achieve this. For scenarios in which the metadata update is not constant, instead of going to the Dev Center web page, you can manually change the type of metadata update for a particular release in the extension, and provide the path to the metadata.
